/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";
import SidebarLeft from "@/components/SidebarLeft";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Robotics Control GPT",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "min-h-screen h-full w-full dark:text-white dark:bg-[#161616] flex"
        )}
      >
        <SidebarLeft />
        {/* sidebar */}
        <main className="min-h-screen  w-full">{children}</main>
      </body>
    </html>
  );
}
